---
- name: Rebuild all hosts
  hosts: all
  tasks:
    - name: Install koan cobbler tool
      yum: name=koan state=present

    - name: Rebuild hosts with default profile
      command: koan --replace-self

    - name: Power cycle hosts
      command: /sbin/reboot

    - name: Wait for hosts to go down
      wait_for: host={{ inventory_host }}
                port=22
                state=stopped
      delegate_to: localhost

    - name: Wait for hosts to come up
      wait_for: host={{ inventory_host }}
                port=22
                delay=300
                timeout=1200
      delegate_to: localhost

    - name: Yum update hosts
      command: yum -y update
